# permissions for end users to view pipelinejobs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pipelinejob-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: cacidy
    app.kubernetes.io/part-of: cacidy
    app.kubernetes.io/managed-by: kustomize
  name: pipelinejob-viewer-role
rules:
- apiGroups:
  - cacidy.io
  resources:
  - pipelinejobs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cacidy.io
  resources:
  - pipelinejobs/status
  verbs:
  - get
