---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - cacidy.io
  resources:
  - runners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cacidy.io
  resources:
  - runners/finalizers
  verbs:
  - update
- apiGroups:
  - cacidy.io
  resources:
  - runners/status
  verbs:
  - get
  - patch
  - update
