---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - cacidy.io
  resources:
  - pipelinejobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cacidy.io
  resources:
  - pipelinejobs/finalizers
  verbs:
  - update
- apiGroups:
  - cacidy.io
  resources:
  - pipelinejobs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - cacidy.io
  resources:
  - runners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cacidy.io
  resources:
  - runners/finalizers
  verbs:
  - update
- apiGroups:
  - cacidy.io
  resources:
  - runners/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - get
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - update
